# Generated by Django 3.0.6 on 2020-05-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbecal',
            name='Dbe',
            field=models.IntegerField(),
        ),
    ]
